In [1]:
import pandas as pd
import numpy as np

In [2]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file inside the Kaggle dataset
file_path = "IMDB Dataset.csv"  # <-- exact file name from the dataset

# Load the dataset as a pandas DataFrame
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
    file_path
)

print("First 5 records:\n", df.head())

/tmp/ipython-input-3298016882.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
First 5 records:
                                               review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

##### lowercasing

In [4]:
df["review"][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [5]:
df["review"][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

##### applying to whole review

In [6]:
df['review']=df['review'].str.lower()

In [7]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

#### Removing tags

In [8]:
df["review"][7]

"this show was an amazing, fresh & innovative idea in the 70's when it first aired. the first 7 or 8 years were brilliant, but things dropped off after that. by 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />it's truly disgraceful how far this show has fallen. the writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. i find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. how can one recognize such brilliance and then see fit to replace it with such mediocrity? i felt i must give 2 stars out of respect for the original cast that made this show such a huge success. as it is now, the show is just awful. i can't believe it's still on the air."

In [9]:
import re

def remove_html_tags(text):
    clean = re.compile(r'<.*?>')
    return re.sub(clean, '', text)

In [10]:
remove_html_tags(df["review"][7])

"this show was an amazing, fresh & innovative idea in the 70's when it first aired. the first 7 or 8 years were brilliant, but things dropped off after that. by 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.it's truly disgraceful how far this show has fallen. the writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. i find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. how can one recognize such brilliance and then see fit to replace it with such mediocrity? i felt i must give 2 stars out of respect for the original cast that made this show such a huge success. as it is now, the show is just awful. i can't believe it's still on the air."

#### apply it to whole col

In [11]:
df["review"]=df["review"].apply(remove_html_tags)

In [12]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [15]:
df["review"][7]

"this show was an amazing, fresh & innovative idea in the 70's when it first aired. the first 7 or 8 years were brilliant, but things dropped off after that. by 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.it's truly disgraceful how far this show has fallen. the writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. i find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. how can one recognize such brilliance and then see fit to replace it with such mediocrity? i felt i must give 2 stars out of respect for the original cast that made this show such a huge success. as it is now, the show is just awful. i can't believe it's still on the air."

#### removing urls

In [17]:
text1 ="Check AI tutorial: https://example.com/ai, PDF: http://files.example.com/ai.pdf, Twitter: https://twitter.com/exampleAI"
text2 ="Watch ML video: https://youtu.be/dQw4w9WgXcQ, Dataset: https://datahub.io/ml, Instagram: https://instagram.com/exampleML"
text3 ="Read paper: https://arxiv.org/pdf/2106.12345.pdf, GitHub: https://github.com/example/research, Slides: http://downloads.example.org/ml.pptx"
text4 ="Join workshop: https://meet.example.com/ml, Materials: https://example.com/resources.zip, Photos: https://photos.example.com/gallery"
text5 ="Blog on AI ethics: https://blog.example.ai/ethics, YouTube: https://youtube.com/watch?v=abcdef, Notebook: https://colab.research.google.com/drive/1XyzABC"

In [18]:
def remove_urls(text):
    url_pattern = r'https?://\S+|www\.\S+'
    return re.sub(url_pattern, '', text).strip()

In [19]:
remove_urls(text2)

'Watch ML video:  Dataset:  Instagram:'

In [20]:
remove_urls(text4)

'Join workshop:  Materials:  Photos:'

##### removing puntucations

In [66]:
import string

In [67]:
exclude=string.punctuation

In [68]:
text1 = "Hello, world! This is an example."
text2 = "Python: easy-to-learn, powerful; flexible?"
text3 = "Wait... what?! Are you sure?!"
text4 = "Email me at example@example.com; I'll reply ASAP!"
text5 = "Good morning!!! How's everything going?"

In [69]:
def remove_punctuation(text):
  for char in exclude:
    text=text.replace(char,'')
  return text

In [70]:
remove_punctuation(text4)

'Email me at exampleexamplecom Ill reply ASAP'

In [71]:
remove_punctuation(text5)

'Good morning Hows everything going'

#### standard way for removing puncs(use this approach)

In [72]:
import string

def remove_puncs(text):
    exclude = string.punctuation
    return text.translate(str.maketrans('', '', exclude))

In [73]:
remove_puncs(text3)

'Wait what Are you sure'

In [82]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Load the train dataset
df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "arkhoshghalb/twitter-sentiment-analysis-hatred-speech",
    "train.csv"
)

/tmp/ipython-input-1060786364.py:5: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'twitter-sentiment-analysis-hatred-speech' dataset.

In [83]:
df.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

#### remove all  punctions from tweets at once

In [84]:
import string

def remove_puncs(text):
    exclude = string.punctuation
    return text.translate(str.maketrans('', '', exclude))

In [86]:
df["tweet"]=df["tweet"].apply(remove_puncs)

In [88]:
df["tweet"]

0         user when a father is dysfunctional and is so...
1        user user thanks for lyft credit i cant use ca...
2                                      bihday your majesty
3        model   i love u take with u all the time in u...
4                     factsguide society now    motivation
                               ...
31957    ate user isz that youuuðððððð...
31958      to see nina turner on the airwaves trying to...
31959    listening to sad songs on a monday morning otw...
31960    user sikh temple vandalised in in calgary wso ...
31961                      thank you user for you follow
Name: tweet, Length: 31962, dtype: object

#### Chat words treatment

In [89]:
slang_dict = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The A**",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "STATS": "Your Sex And Age",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTF": "What The F**k",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired"
}

In [90]:
def chat_convert(text):
    new_text = []
    for word in text.split():  # split the input text into words
        # if the word is in the slang dictionary, replace it; else keep it
        new_text.append(slang_dict.get(word.upper(), word))
    return ' '.join(new_text)

In [91]:
message = "LOL I will BRB, AFK for a while"

In [92]:
chat_convert(message)

'Laughing Out Loud I will BRB, Away From Keyboard for a while'

In [93]:
chat_convert("fyi kathmandu is capital of Nepal")

'For Your Information kathmandu is capital of Nepal'

#### spelling corrections

In [96]:
from textblob import TextBlob

In [97]:
wrong_text= "cartian condiitons several generatio aer modified in same manner"

In [98]:
txtblb= TextBlob(wrong_text)
txtblb.correct().string

'certain conditions several generation her modified in same manner'

#### removing stopwords

In [99]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [100]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [101]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word.lower() not in stopwords.words('english'):
            new_text.append(word)
    return ' '.join(new_text)

In [102]:
sample_text="She said that she would call me when she arrives at the office, but I haven’t heard from her yet."

In [103]:
remove_stopwords(sample_text)

'said would call arrives office, haven’t heard yet.'

In [104]:
df.head()

   id  label                                              tweet
0   1      0   user when a father is dysfunctional and is so...
1   2      0  user user thanks for lyft credit i cant use ca...
2   3      0                                bihday your majesty
3   4      0  model   i love u take with u all the time in u...
4   5      0               factsguide society now    motivation

In [109]:
df["tweet"].apply(remove_stopwords)

0        user father dysfunctional selfish drags kids d...
1        user user thanks lyft credit cant use cause do...
2                                           bihday majesty
3        model love u take u time urð± ðððð...
4                            factsguide society motivation
                               ...
31957    ate user isz youuuððððððð...
31958    see nina turner airwaves trying wrap mantle ge...
31959      listening sad songs monday morning otw work sad
31960    user sikh temple vandalised calgary wso condem...
31961                                    thank user follow
Name: tweet, Length: 31962, dtype: object

#### Handling emojis

###### we have two options->either remove the emojis or replace them with their textual meaning

In [110]:
import re

def remove_emojis(text):

    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # Emoticons
        u"\U0001F300-\U0001F5FF"  # Symbols & Pictographs
        u"\U0001F680-\U0001F6FF"  # Transport & Map Symbols
        u"\U0001F1E0-\U0001F1FF"  # Flags
        u"\U00002700-\U000027BF"  # Dingbats
        u"\U0001F900-\U0001F9FF"  # Supplemental Symbols & Pictographs
        u"\U00002600-\U000026FF"  # Misc symbols
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [112]:
text = "Hallo 😊! i love Python 🐍🚀"
remove_emojis(text)

'Hallo ! i love Python '

In [113]:
remove_emojis("lmaoooooooooooooooo😂🤣")

'lmaoooooooooooooooo'

#### Tokenization

###### using split functions

In [114]:
# word tokenizations
txt="I am from Birtamode"
txt.split()

['I', 'am', 'from', 'Birtamode']

In [116]:
# sentence tokenizations
txt="I am from Birtamode. I live near lfes school. blablaabla"
txt.split('.')

['I am from Birtamode', ' I live near lfes school', ' blablaabla']

In [119]:
# problem with split
txt = "I live in the U.S. I love it. The number is 3.5. Dr. Bob is here."

# Using simple split('.') method
sentences_split = txt.split('.')
print(sentences_split)

['I live in the U', 'S', ' I love it', ' The number is 3', '5', ' Dr', ' Bob is here', '']

txt.split('.'), Python cuts the text at every dot without thinking:

"U.S." → becomes 'U' and 'S' (abbreviation broken)

"3.5" → becomes '3' and '5' (number broken)

"Dr. Bob" → becomes 'Dr' and 'Bob is here' (title broken)

#### using regex

In [120]:
import re
text='I am going to delhi!'
tokens=re.findall("[\w']+",text)
tokens

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-1062498329.py:3: SyntaxWarning: invalid escape sequence '\w'
  tokens=re.findall("[\w']+",text)

['I', 'am', 'going', 'to', 'delhi']

In [121]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

In [122]:
text=re.compile(' [.!?] ').split(text)

In [123]:
text

["Lorem Ipsum is simply dummy text of the printing and typesetting industry? \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, \nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

#### best sol- NLTK

In [134]:
import nltk

# download the correct tokenizer data for newer NLTK versions
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [136]:
from nltk.tokenize import word_tokenize, sent_tokenize

txt = "I am going to korea!"
words = word_tokenize(txt)
print(words)

['I', 'am', 'going', 'to', 'korea', '!']

In [138]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

In [139]:
word_tokenize(text)

['Lorem',
 'Ipsum',
 'is',
 'simply',
 'dummy',
 'text',
 'of',
 'the',
 'printing',
 'and',
 'typesetting',
 'industry',
 '?',
 'Lorem',
 'Ipsum',
 'has',
 'been',
 'the',
 'industry',
 "'s",
 'standard',
 'dummy',
 'text',
 'ever',
 'since',
 'the',
 '1500s',
 ',',
 'when',
 'an',
 'unknown',
 'printer',
 'took',
 'a',
 'galley',
 'of',
 'type',
 'and',
 'scrambled',
 'it',
 'to',
 'make',
 'a',
 'type',
 'specimen',
 'book',
 '.']

In [140]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

In [141]:
word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [143]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [146]:
#some prolbem in sent6, the gmail got tokenize  too.

In [147]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

####  one of the another best is spacy

In [148]:
import spacy
nlp=spacy.load('en_core_web_sm')

#### convert sentences into docs

In [155]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

In [156]:
doc1=nlp(sent5)
doc2=nlp(sent6)
doc3=nlp(sent7)

In [157]:
for token in doc1:
  print(token)

I
have
a
Ph
.
D
in
A.I

In [158]:
for token in doc2:
  print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [159]:
for token in doc3:
  print(token)

A
5
km
ride
cost
$
10.50